Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

# Numpy

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

In [ ]:
a1=np.random.uniform(0,20, size=(4,7))
a1

array([[18.83727412,  3.50632178,  6.10900569, 13.49370009, 18.35324984,
        15.66384705,  1.63883326],
       [ 8.61990977,  1.31361202, 16.4101097 ,  2.74465634,  1.67707711,
        19.99423918, 11.33239888],
       [ 8.43520654,  5.74593128, 14.40728958,  3.14634001, 19.71629472,
        17.39697664, 10.50714222],
       [ 6.99006857, 18.28517478,  3.33723968, 10.5231591 , 15.26350006,
        19.82816341,  0.90604799]])

In [ ]:
a2 = (a1-a1.min()) / a1.max()-a1.min()*(1-0)+0
a2

array([[-0.00922837, -0.77599684, -0.64582515, -0.27648405, -0.03343655,
        -0.16794544, -0.86939817],
       [-0.52024378, -0.88566392, -0.13062155, -0.81409109, -0.86748543,
         0.04863655, -0.38458024],
       [-0.5294816 , -0.6639841 , -0.23079141, -0.79400112,  0.03473533,
        -0.08126399, -0.42585497],
       [-0.60175932, -0.03684129, -0.78445339, -0.42505389, -0.18796855,
         0.04033037, -0.90604799]])

In [ ]:
a2.min(),a2.max()

(-0.9060479937045374, 0.04863655389304222)

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
mat = np.random.randint(0,11, size=(8,10))
mat

array([[10,  6,  8,  9,  4,  5, 10,  2,  4,  7],
       [ 8,  8,  5,  5,  7,  0,  5,  8,  2,  7],
       [ 6,  5,  3,  1,  5,  8,  2,  2,  7,  4],
       [ 4,  8,  9,  8,  5,  5,  6, 10,  9, 10],
       [ 7,  8,  0,  4,  5,  1,  5,  9,  0,  7],
       [ 2,  2,  8,  3,  2,  3,  6,  8,  8,  9],
       [ 0,  1,  4,  9,  0, 10,  9,  6,  5, 10],
       [ 2,  8,  5,  1,  9,  0,  3,  4,  5,  9]])

In [ ]:
minsum=mat.sum(axis=1) #суммирование всех строчек
minsum

array([65, 55, 43, 74, 46, 51, 54, 46])

In [ ]:
minsum.argmin() #возвращает индексы минимальных значений по оси (43)

2

In [ ]:
mat[minsum.argmin()] #вывели строку с минимальной суммой

array([6, 5, 3, 1, 5, 8, 2, 2, 7, 4])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
a3=np.random.randint(0,3, size=5)
a3

array([2, 0, 1, 2, 0])

In [ ]:
a4=np.random.randint(1,5, size=5)
a4

array([1, 2, 4, 3, 3])

In [ ]:
np.sqrt(np.sum((a3-a4)**2))

4.898979485566356

In [ ]:
#можно использовать формулу из модуля линала
np.linalg.norm(a3-a4)

4.898979485566356

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A=np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B=np.array([[3, -1], [2, 1]])
C=np.array([[7, 21], [11, 8], [8, 4]])

In [ ]:
#X=A^-1*(-C)*B^-1
X=np.dot(np.dot(np.linalg.inv(A),(-C)), np.linalg.inv(B))
X

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
data = np.loadtxt('minutes_n_ingredients.csv', dtype='int32', delimiter = ',', skiprows =1)
data[:5] #вывод первых пяти строк

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
(data[:,1:].mean(axis=0), #столбцы
 data[:,1:].min(axis=0),
 data[:,1:].max(axis=0),
 np.median(data[:,1:],axis=0))


(array([2.16010017e+04, 9.05528000e+00]),
 array([0, 1], dtype=int32),
 array([2147483647,         39], dtype=int32),
 array([40.,  9.]))

In [ ]:
data[:,1:]

array([[ 60,  16],
       [ 25,   7],
       [ 10,   6],
       ...,
       [ 65,  15],
       [  5,   4],
       [140,  14]], dtype=int32)

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля  𝑞0.75 .

In [ ]:
q=np.quantile(data[:,1],q=0.75) #посчитали какой квантиль
q

65.0

In [ ]:
data[:,1]=data[:,1].clip(max=q) #обрезали все что больше 65
data[:,1].max()

65

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
display(data[data[:,1]==0].shape)
data[data[:,1]==0,1]=1

(479, 3)

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
len(np.unique(data[:,0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
len(np.unique(data[:,2]))

37

In [ ]:
np.unique(data[:,2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39], dtype=int32)

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
data[data[:,2]<=5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
(data[:,2]/data[:,1]).max()

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
rows = data[:,1].argsort()[-100:] 
data[rows, 2].mean()

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
data[np.random.randint(0, len(data), 10)]

array([[491276,     40,      5],
       [174570,     45,      9],
       [ 23791,     40,     12],
       [ 94065,     40,      8],
       [265000,     65,     14],
       [529119,     65,     16],
       [203570,     30,     14],
       [235367,     55,      8],
       [303765,     65,     11],
       [ 92494,     32,     12]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
len(data[data[:,2]<data[:,2].mean()])/len(data[:,2])

0.58802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
big_dataset = np.zeros((100000,4), dtype=np.int32)
big_dataset[:,:3] = data

big_dataset[:,3]=((data[:,1]<=20) & (data[:,2]<=5)).astype(np.int32)
big_dataset

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]], dtype=int32)

13. Выведите процент "простых" рецептов в датасете

In [ ]:
len(big_dataset[big_dataset[:,3]==1])/len(big_dataset[:,3])

0.09552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
data_small=data[:,2] < 10
data_stand=(data[:, 2] > 10) & (data[:,1] < 20)
data_dlin=data[:,2] >= 20
display(len(data_small))
display(data_stand.sum())
data_dlin.sum()
lenght=min(data_small.sum(),data_stand.sum(),data_dlin.sum()) #выбираем наим количество строк из одной из трех категорий
np.array([data[data_small][0:lenght],data[data_stand][0:lenght],data[data_dlin][0:lenght]]).shape


100000

1849

(3, 1074, 3)

# Новый раздел